In [1]:
import numpy as np 
import pandas as pd

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [6]:
df = pd.read_csv('airbnb-listings.csv', sep=',')
df.head()

C:\Users\hsupo\AppData\Local\Temp\ipykernel_43176\4266839384.py:1: DtypeWarning: Columns (0,2,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('airbnb-listings.csv', sep=',')

,ID,Listing Url,Scrape ID,Last Scraped,Name,Summary,Space,Description,Experiences Offered,Neighborhood Overview,...,Review Scores Communication,Review Scores Location,Review Scores Value,License,Jurisdiction Names,Cancellation Policy,Calculated host listings count,Reviews per Month,Geolocation,Features
0,4008728,https://www.airbnb.com/rooms/4008728,20170402075052,2017-04-02,"Luxurious 3 bedroom, centrum, 180m2",‪This luxurious apartment is situated in the c...,In the heart of hip & lively Amsterdam Centrum...,‪This luxurious apartment is situated in the c...,none,There is a wide variety of cafes and restauran...,...,10.0,10.0,9.0,NaN,Amsterdam,strict,1.0,1.52,"52.36523660409065, 4.878249575101092","Host Has Profile Pic,Host Identity Verified,Is..."
1,7778612,https://www.airbnb.com/rooms/7778612,20170402075052,2017-04-02,Luxury apartment in city centre,"Beautiful, large (105m2, 2 floors) and quiet a...",1 living room 1 dining room 2 bedrooms 1 bathr...,"Beautiful, large (105m2, 2 floors) and quiet a...",none,Within a few minutes walking you'll be in the ...,...,10.0,10.0,9.0,NaN,Amsterdam,strict,1.0,0.81,"52.367309030897516, 4.8738407410699915","Host Is Superhost,Host Has Profile Pic,Host Id..."
2,8264596,https://www.airbnb.com/rooms/8264596,20170402075052,2017-04-02,Cosy apartment across Vondelpark,This central located apartment will make you f...,NaN,This central located apartment will make you f...,none,NaN,...,10.0,10.0,10.0,NaN,Amsterdam,flexible,1.0,0.05,"52.361943953804776, 4.866686522141489","Host Has Profile Pic,Host Identity Verified,Is..."
3,2180729,https://www.airbnb.com/rooms/2180729,20170402075052,2017-04-02,Spacious City Apartment Oud-West,Living like an Amsterdam resident in this ligh...,There are 2 bedrooms each with a double bed. I...,Living like an Amsterdam resident in this ligh...,none,The 85 m2 apartment is located on a quiet stre...,...,9.0,9.0,9.0,NaN,Amsterdam,flexible,1.0,0.62,"52.37014616115532, 4.866281767968382","Host Has Profile Pic,Host Identity Verified,Is..."
4,14463171,https://www.airbnb.com/rooms/14463171,20170402075052,2017-04-02,Cosy Studio Apartment Center Amsterdam,Studio Apartment Centre Amsterdam Perfect stud...,NaN,Studio Apartment Centre Amsterdam Perfect stud...,none,NaN,...,8.0,9.0,9.0,NaN,Amsterdam,moderate,1.0,2.04,"52.368817829014425, 4.871249476925455",Host Has Profile Pic

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494954 entries, 0 to 494953
Data columns (total 89 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              494954 non-null  object
 1   Listing Url                     494954 non-null  object
 2   Scrape ID                       494954 non-null  object
 3   Last Scraped                    494953 non-null  object
 4   Name                            494536 non-null  object
 5   Summary                         478753 non-null  object
 6   Space                           347018 non-null  object
 7   Description                     494794 non-null  object
 8   Experiences Offered             494954 non-null  object
 9   Neighborhood Overview           291604 non-null  object
 10  Notes                           197590 non-null  object
 11  Transit                         303786 non-null  object
 12  Access                          268399 non-null  object
 13  Interaction                     256459 non-null  object
 14  House Rules                     297015 non-null  object
 15  Thumbnail Url                   400120 non-null  object
 16  Medium Url                      400119 non-null  object
 17  Picture Url                     494220 non-null  object
 18  XL Picture Url                  400120 non-null  object
 19  Host ID                         494954 non-null  int64
 20  Host URL                        494954 non-null  object
 21  Host Name                       494449 non-null  object
 22  Host Since                      494449 non-null  object
 23  Host Location                   492691 non-null  object
 24  Host About                      296274 non-null  object
 25  Host Response Time              379885 non-null  object
 26  Host Response Rate              379884 non-null  float64
 27  Host Acceptance Rate            42258 non-null   object
 28  Host Thumbnail Url              494449 non-null  object
 29  Host Picture Url                494449 non-null  object
 30  Host Neighbourhood              370737 non-null  object
 31  Host Listings Count             494449 non-null  float64
 32  Host Total Listings Count       494448 non-null  float64
 33  Host Verifications              494114 non-null  object
 34  Street                          494953 non-null  object
 35  Neighbourhood                   345403 non-null  object
 36  Neighbourhood Cleansed          494953 non-null  object
 37  Neighbourhood Group Cleansed    102163 non-null  object
 38  City                            494500 non-null  object
 39  State                           445158 non-null  object
 40  Zipcode                         475338 non-null  object
 41  Market                          489299 non-null  object
 42  Smart Location                  494952 non-null  object
 43  Country Code                    494952 non-null  object
 44  Country                         494951 non-null  object
 45  Latitude                        494953 non-null  float64
 46  Longitude                       494953 non-null  float64
 47  Property Type                   494943 non-null  object
 48  Room Type                       494953 non-null  object
 49  Accommodates                    494891 non-null  float64
 50  Bathrooms                       493428 non-null  float64
 51  Bedrooms                        494328 non-null  float64
 52  Beds                            494037 non-null  float64
 53  Bed Type                        494953 non-null  object
 54  Amenities                       490466 non-null  object
 55  Square Feet                     12209 non-null   float64
 56  Price                           486996 non-null  float64
 57  Weekly Price                    97747 non-null   float64
 58  Monthly Price                   96091 non-null   float64
 59  Security Deposit                204012 non-null  float64
 60  Cleaning Fee                    315715 non-null  float64
 61  Guests Included                 494952 non-null  float64
 62  Extra People                    494917 non-null  float64
 63  Minimum Nights                  494952 non-null  float64
 64  Maximum Nights                  494952 non-null  float64
 65  Calendar Updated                494953 non-null  object
 66  Has Availability                9307 non-null    object
 67  Availability 30                 494952 non-null  float64
 68  Availability 60                 494952 non-null  float64
 69  Availability 90                 494952 non-null  float64
 70  Availability 365                494952 non-null  float64
 71  Calendar last Scraped           494952 non-null  object
 72  Number of Reviews               494952 non-null  float64
 73  First Review                    372947 non-null  object
 74  Last Review                     373055 non-null  object
 75  Review Scores Rating            367134 non-null  float64
 76  Review Scores Accuracy          366237 non-null  float64
 77  Review Scores Cleanliness       366479 non-null  float64
 78  Review Scores Checkin           365918 non-null  float64
 79  Review Scores Communication     366434 non-null  float64
 80  Review Scores Location          365969 non-null  float64
 81  Review Scores Value             365873 non-null  float64
 82  License                         14596 non-null   object
 83  Jurisdiction Names              134553 non-null  object
 84  Cancellation Policy             494952 non-null  object
 85  Calculated host listings count  494087 non-null  float64
 86  Reviews per Month               372947 non-null  float64
 87  Geolocation                     494953 non-null  object
 88  Features                        494648 non-null  object
dtypes: float64(33), int64(1), object(55)
memory usage: 336.1+ MB

In [8]:
df.describe()

,Host ID,Host Response Rate,Host Listings Count,Host Total Listings Count,Latitude,Longitude,Accommodates,Bathrooms,Bedrooms,Beds,...,Number of Reviews,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Calculated host listings count,Reviews per Month
count,4.949540e+05,379884.000000,494449.000000,494448.000000,494953.000000,494953.000000,494891.000000,493428.000000,494328.000000,494037.000000,...,494952.000000,367134.000000,366237.000000,366479.000000,365918.000000,366434.000000,365969.000000,365873.000000,494087.000000,372947.000000
mean,3.234417e+07,93.376549,9.549721,9.549738,38.042292,-15.020974,3.311584,1.249632,1.378322,1.934525,...,16.740850,92.913988,9.527773,9.328483,9.692770,9.709972,9.471171,9.323047,6.869659,1.479523
std,3.172156e+07,17.592441,57.199523,57.199579,22.941429,70.364294,2.094052,0.607029,0.942508,1.488128,...,32.336701,8.543725,0.852536,1.035356,0.727947,0.719978,0.803260,0.903585,41.977381,1.731931
min,1.900000e+01,0.000000,0.000000,0.000000,-38.224427,-123.218712,1.000000,0.000000,0.000000,0.000000,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,6.886060e+06,98.000000,1.000000,1.000000,38.913119,-73.969216,2.000000,1.000000,1.000000,1.000000,...,1.000000,90.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.320000
50%,2.188181e+07,100.000000,1.000000,1.000000,42.310894,2.137584,2.000000,1.000000,1.000000,1.000000,...,4.000000,95.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.880000
75%,4.792177e+07,100.000000,3.000000,3.000000,51.375424,12.444849,4.000000,1.000000,2.000000,2.000000,...,18.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,2.030000
max,1.350885e+08,100.000000,1114.000000,1114.000000,55.994889,153.637837,21.000000,10.000000,96.000000,19.000000,...,735.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,752.000000,223.000000

In [9]:
selected_columns = ['ID', 'Name', 'Neighborhood Overview', 'Transit', 'Host ID', 'Host Name', 'Host Since', 'Host About', 'Host Response Time', 'Host Response Rate', 'Street', 'Neighbourhood', 'City', 'Zipcode', 'Country', 'Latitude', 'Longitude', 'Property Type', 'Accommodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Bed Type', 'Amenities', 'Price', 'Guests Included', 'Number of Reviews', 'Last Review', 'Review Scores Rating', 'Review Scores Cleanliness', 'Review Scores Location', 'Cancellation Policy', 'Geolocation']
df_selected = df.loc[:, selected_columns]
df_selected.head(5)

,ID,Name,Neighborhood Overview,Transit,Host ID,Host Name,Host Since,Host About,Host Response Time,Host Response Rate,...,Amenities,Price,Guests Included,Number of Reviews,Last Review,Review Scores Rating,Review Scores Cleanliness,Review Scores Location,Cancellation Policy,Geolocation
0,4008728,"Luxurious 3 bedroom, centrum, 180m2",There is a wide variety of cafes and restauran...,NaN,20786453,Lithal,2014-09-01,Hi there! As I love to travel myself I know ho...,within a day,50.0,...,"TV,Internet,Wireless Internet,Kitchen,Pets all...",600.0,4.0,31.0,2016-11-27,89.0,8.0,10.0,strict,"52.36523660409065, 4.878249575101092"
1,7778612,Luxury apartment in city centre,Within a few minutes walking you'll be in the ...,Public transport is very close - 100 meters,11964927,Hein,2014-02-05,I live together with my girlfriend in our apar...,within a few hours,100.0,...,"TV,Cable TV,Internet,Wireless Internet,Kitchen...",175.0,2.0,15.0,2017-01-19,99.0,9.0,10.0,strict,"52.367309030897516, 4.8738407410699915"
2,8264596,Cosy apartment across Vondelpark,NaN,NaN,23669273,Matthieu,2014-11-12,NaN,NaN,NaN,...,"TV,Cable TV,Internet,Wireless Internet,Kitchen...",125.0,1.0,1.0,2015-09-22,100.0,10.0,10.0,flexible,"52.361943953804776, 4.866686522141489"
3,2180729,Spacious City Apartment Oud-West,The 85 m2 apartment is located on a quiet stre...,A few important spots in the city: - van Gogh ...,9238680,Bas,2013-10-05,NaN,within a day,100.0,...,"TV,Cable TV,Internet,Wireless Internet,Kitchen...",130.0,2.0,22.0,2016-07-19,97.0,9.0,9.0,flexible,"52.37014616115532, 4.866281767968382"
4,14463171,Cosy Studio Apartment Center Amsterdam,NaN,NaN,89112644,Pablo,2016-08-10,NaN,within a day,100.0,...,"TV,Wireless Internet,Kitchen,Heating,Smoke det...",80.0,1.0,16.0,2017-03-06,78.0,8.0,9.0,moderate,"52.368817829014425, 4.871249476925455"

In [11]:
df_selected.to_csv('airbnb_listings_selected.csv', index=False)